### ISSUE TITLE
[qn] Where is sketchybar installed?

### ISSUE THREAD

**Issue by tanshunyuan** [GiveNoCode/nix-setup#12]
I came across your configuration through https://github.com/FelixKratz/SketchyBar/issues/553#issuecomment-2471760488.

I was looking through it to resolve my own sketchybar issues (they've been solved), but I'm curious at which point you installed `sketchy bar`, as I didn't find any declaration for it.

I see that you've the following tap
```
    taps = [
      "homebrew/services"
      "nikitabobko/tap"
      "FelixKratz/formulae"
    ];
```
so I was expecting `sketchybar` to be in the `brews` section but there wasn't any
```
    brews = [
      "wget" # download tool
      "curl" # no not install curl via nixpkgs, it's not working well on macOS!

      "switchaudio-osx"
      "borders"
      "scrcpy"
    ];
```

**Comment by GiveNoCode** [comment]
Thanks for checking out my configuration and for your thoughtful comment! I’m glad to hear you resolved your SketchyBar issues.

I currently manage SketchyBar via Nix within [this file](https://github.com/GiveNoCode/nix-setup/blob/a4be3a9480a8556f9d65b02fe5e7cfbb5cdca95b/modules/darwin/sketchybar.nix#L3) You’re right about the FelixKratz/formulae tap—it’s leftover from an older setup and not needed anymore. I’ll remove it to avoid confusion.

I’m also considering switching to a Homebrew installation for easier access to the latest versions. Thanks again for pointing this out, and I hope my setup was helpful!
